### ISSUE TITLE
Using AutoWebPerf for PWA and web components like web view in an android device

### ISSUE THREAD

**Issue by chatur-sriganesh** [GoogleChromeLabs/AutoWebPerf#66]
Hi,

Is there a way we can leverage this tool to get performance metrics for web components present in an android app?
Our app primarily consists of PWA pages and some web views.

Any suggestions on the same would be greatly helpful! @jonchenn 

Thanks,
Chatur

**Comment by jonchenn** [comment]
Hi @chatur-sriganesh, thanks for the idea. Very interesting. The current gatherers doesn't support your use case, because either WebPageTest or PageSpeedInsight needs to be able to access to your page web to measure the performance. 

However, one possible route is to build your own custom gatherer that plays along with the WebView or PWA from your Android app, and let the gatherer to capture those web performance events, like page load time, FCP, LCP, CLS, or other web vitals. But the challenges remain the same as you'll need to find a way execute the AWP tool, and/or have your custom gather to be able to access your own WebView of your Android app.

Hope this helps.
